In [2]:
%matplotlib notebook
%pylab

Using matplotlib backend: nbAgg
Populating the interactive namespace from numpy and matplotlib


/home/brian/anaconda3/lib/python3.7/site-packages/IPython/core/magics/pylab.py:160: UserWarning: pylab import has clobbered these variables: ['beta']
`%matplotlib` prevents importing * from pylab and numpy
  "\n`%matplotlib` prevents importing * from pylab and numpy"


In [14]:
alpha=0
beta=0
m=7
q=lambda x:0
p=lambda x:0
r=lambda x:0
a=0;b=1
h=(b-a)/(m+1)
x=zeros(m)
#x[m-1]=1
A=zeros((m,m))
#A[m-1,m-1]=(-2/(h**2))-q(b)
F=zeros(m)
rh=zeros(m)
rh[m-1]=r(b)
e1=zeros(m);em=zeros(m)
e1[0]=1;em[m-1]=1
for j in range(m):
    x[j]=(1+j)*h
    f1=(1/(h**2))+(p(x[j]))/2*h
    f2=(1/(h**2))-(p(x[j]))/2*h
    rh[j]=r(x[j])
    
    A[j,j]=(-2/(h**2))-q(x[j])
    if  j == 0:
        A[j,j+1]=(1/(h**2))-(p(x[j]))/(2*h)
        F=rh-(f1*alpha*e1)-(f2*beta*em)
        
    elif 0<j<=m-2:
        A[j,j+1]=(1/(h**2))-p(x[j])
        A[j,j-1] = (1/h**2) + p(x[j])/(2*h)
        F=rh
    else:
        A[j,j-1] = (1/h**2) + p(x[j])/(2*h)    
        F=rh-(f1*alpha*e1)-(f2*beta*em)
#linalg.solve(A,transpose(F))
A

array([[-128.,   64.,    0.,    0.,    0.,    0.,    0.],
       [  64., -128.,   64.,    0.,    0.,    0.,    0.],
       [   0.,   64., -128.,   64.,    0.,    0.,    0.],
       [   0.,    0.,   64., -128.,   64.,    0.,    0.],
       [   0.,    0.,    0.,   64., -128.,   64.,    0.],
       [   0.,    0.,    0.,    0.,   64., -128.,   64.],
       [   0.,    0.,    0.,    0.,    0.,   64., -128.]])

In [7]:
F

array([0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75])

In [8]:
#exact solution
uexact=lambda x: (x-1)*(tan(x))
Uexact=[]
h=[]
m=[10,20,40,80,160]
for j in m:
    xj=zeros(j)
    for i in range(1,j):
        hi=1/(j+1)
        xj[i]=(i+1)*hi
    h.append(hi)
    u_exact=uexact(xj)
    Uexact.append(u_exact)
    print('\nExact solution for m=',j,'is', u_exact)
    #figure(j)
    #plot(xj,u_exact)


array([0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75])

In [ ]:
def fd2tpbvp(p,q,r,alpha,beta,m):
    '''
    Arguments
    ---------
    p,q,r: are function coefficients in the equation u''=p(x)u' + q(x)u +r(x)
    alpha and beta: are boundary function points:u(0) and u(1) respectively
    m: number of interior discretization points
    
    Parameters
    ----------
    A: is m by m interior matrix
    e1 and em: are first and last columns of and m by m identity matrix respectively
    rh: is a column vector of r(x)
    
    Returns
    -------
    U_h: second derivative of fuction u(x)
    '''
    h=(b-a)/(m+1)
    A=zeros((m,m))
    F=zeros(m)
    x=zeros(m)
    
    for j in range(m):
        x[j]=(j+1)*h
        A[j,j]=(-2/(h**2))-q(x[j])
        f1=(1/(h**2))+(p(x[j]))/(2*h)
        f2=(1/(h**2))-(p(x[j]))/(2*h)
        
        if j == 0:
            A[j,j+1]=(1/(h**2))-(p(x[j]))/(2*h)
            F[j]=rh(x[j])-(f1*alpha*e1)

        elif 0<j<=m-2:
            A[j,j+1]=(1/(h**2))-p(x[j])/
            A[j,j-1] = (1/h**2) + p(x[j])/(2*h)
            F=rh
        else:
            A[j,j-1] = (1/h**2) + p(x[j])/(2*h)    
            F=rh-(f1*alpha*e1)-(f2*beta*em)
    U_h=linalg.solve(A,F) #inverse(A)*F
    return U_h     
        

In [ ]:
a=0 ;b=2*pi
m=99

def f(x):
    return (-4*cos(2*x))

sig0=0; sig1= 0

h=(b-a)/(m+1)
c=1/(h**2)
x=zeros(m+2)
A=zeros((m+3,m+3)) #(m+3)-by-(m+3) matrix
F=zeros(m+3)

for j in range(m+2):
    x[j]=a+j*h
    A[j,j]=-2*c
    
    if j == 0:
        A[j,j+1]=2*c
        A[j,-1]=1/2
        A[-1,j]=1/2
        F[j]=f(a)+(2/h)*sig0
        
    elif 0<j<m+1:
        A[j,j+1]=c
        A[j,j-1]=c
        A[j,-1]=1
        A[-1,j]=1
        F[j]=f(x[j])
        
    else:
        A[j,j+1]=1/2
        A[j,j-1]=2*c
        A[-1,j]=1/2
        F[j]=f(b)-(2/h)*sig1
        
U=solve(A,F) 